/*
 * Wish Fabric.Core Api - Middleware to Fabric.Core
 *
 * Wish Fabric.Core API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DatabaseUserInfo :  IEquatable<DatabaseUserInfo>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DatabaseUserInfo" /> class.
        /// </summary>
        /// <param name="DbUser">Database user identifier.</param>
        /// <param name="Password">Password.</param>
        /// <param name="Grants">Grants.</param>
        public DatabaseUserInfo(string DbUser = null, string Password = null, List<Grant> Grants = null)
        {
            this.DbUser = DbUser;
            this.Password = Password;
            this.Grants = Grants;
            
        }

        /// <summary>
        /// Database user identifier
        /// </summary>
        /// <value>Database user identifier</value>
        [DataMember(Name="db_user")]
        public string DbUser { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name="password")]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets Grants
        /// </summary>
        [DataMember(Name="grants")]
        public List<Grant> Grants { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DatabaseUserInfo {\n");
            sb.Append("  DbUser: ").Append(DbUser).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Grants: ").Append(Grants).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((DatabaseUserInfo)obj);
        }

        /// <summary>
        /// Returns true if DatabaseUserInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of DatabaseUserInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DatabaseUserInfo other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.DbUser == other.DbUser ||
                    this.DbUser != null &&
                    this.DbUser.Equals(other.DbUser)
                ) && 
                (
                    this.Password == other.Password ||
                    this.Password != null &&
                    this.Password.Equals(other.Password)
                ) && 
                (
                    this.Grants == other.Grants ||
                    this.Grants != null &&
                    this.Grants.SequenceEqual(other.Grants)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.DbUser != null)
                    hash = hash * 59 + this.DbUser.GetHashCode();
                if (this.Password != null)
                    hash = hash * 59 + this.Password.GetHashCode();
                if (this.Grants != null)
                    hash = hash * 59 + this.Grants.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(DatabaseUserInfo left, DatabaseUserInfo right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DatabaseUserInfo left, DatabaseUserInfo right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
