/*
 * Wish Fabric Api - Middleware to Fabric
 *
 * Wish Fabric API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class HostingAccount :  IEquatable<HostingAccount>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HostingAccount" /> class.
        /// </summary>
        /// <param name="HostingName">hosting account (primary domain) (required).</param>
        /// <param name="HostingAdminEmail">admin email for hosting account (required).</param>
        /// <param name="DiskQuota">webspace quota MB (0&#x3D;unlimited) (required).</param>
        /// <param name="FtpQuota">FtpQuota (required).</param>
        /// <param name="BandwidthQuota">BandwidthQuota (required).</param>
        /// <param name="DbQuota">DbQuota (required).</param>
        /// <param name="DbMaxSize">DbMaxSize (required).</param>
        /// <param name="Region">optional, specify the region of provisioning (datacenter).</param>
        public HostingAccount(string HostingName = null, string HostingAdminEmail = null, long? DiskQuota = null, int? FtpQuota = null, long? BandwidthQuota = null, int? DbQuota = null, int? DbMaxSize = null, string Region = null)
        {
            // to ensure "HostingName" is required (not null)
            if (HostingName == null)
            {
                throw new InvalidDataException("HostingName is a required property for HostingAccount and cannot be null");
            }
            else
            {
                this.HostingName = HostingName;
            }
            // to ensure "HostingAdminEmail" is required (not null)
            if (HostingAdminEmail == null)
            {
                throw new InvalidDataException("HostingAdminEmail is a required property for HostingAccount and cannot be null");
            }
            else
            {
                this.HostingAdminEmail = HostingAdminEmail;
            }
            // to ensure "DiskQuota" is required (not null)
            if (DiskQuota == null)
            {
                throw new InvalidDataException("DiskQuota is a required property for HostingAccount and cannot be null");
            }
            else
            {
                this.DiskQuota = DiskQuota;
            }
            // to ensure "FtpQuota" is required (not null)
            if (FtpQuota == null)
            {
                throw new InvalidDataException("FtpQuota is a required property for HostingAccount and cannot be null");
            }
            else
            {
                this.FtpQuota = FtpQuota;
            }
            // to ensure "BandwidthQuota" is required (not null)
            if (BandwidthQuota == null)
            {
                throw new InvalidDataException("BandwidthQuota is a required property for HostingAccount and cannot be null");
            }
            else
            {
                this.BandwidthQuota = BandwidthQuota;
            }
            // to ensure "DbQuota" is required (not null)
            if (DbQuota == null)
            {
                throw new InvalidDataException("DbQuota is a required property for HostingAccount and cannot be null");
            }
            else
            {
                this.DbQuota = DbQuota;
            }
            // to ensure "DbMaxSize" is required (not null)
            if (DbMaxSize == null)
            {
                throw new InvalidDataException("DbMaxSize is a required property for HostingAccount and cannot be null");
            }
            else
            {
                this.DbMaxSize = DbMaxSize;
            }
            this.Region = Region;
            
        }

        /// <summary>
        /// hosting account (primary domain)
        /// </summary>
        /// <value>hosting account (primary domain)</value>
        [DataMember(Name="hosting_name")]
        public string HostingName { get; set; }

        /// <summary>
        /// admin email for hosting account
        /// </summary>
        /// <value>admin email for hosting account</value>
        [DataMember(Name="hosting_admin_email")]
        public string HostingAdminEmail { get; set; }

        /// <summary>
        /// webspace quota MB (0=unlimited)
        /// </summary>
        /// <value>webspace quota MB (0=unlimited)</value>
        [DataMember(Name="disk_quota")]
        public long? DiskQuota { get; set; }

        /// <summary>
        /// Gets or Sets FtpQuota
        /// </summary>
        [DataMember(Name="ftp_quota")]
        public int? FtpQuota { get; set; }

        /// <summary>
        /// Gets or Sets BandwidthQuota
        /// </summary>
        [DataMember(Name="bandwidth_quota")]
        public long? BandwidthQuota { get; set; }

        /// <summary>
        /// Gets or Sets DbQuota
        /// </summary>
        [DataMember(Name="db_quota")]
        public int? DbQuota { get; set; }

        /// <summary>
        /// Gets or Sets DbMaxSize
        /// </summary>
        [DataMember(Name="db_max_size")]
        public int? DbMaxSize { get; set; }

        /// <summary>
        /// optional, specify the region of provisioning (datacenter)
        /// </summary>
        /// <value>optional, specify the region of provisioning (datacenter)</value>
        [DataMember(Name="region")]
        public string Region { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HostingAccount {\n");
            sb.Append("  HostingName: ").Append(HostingName).Append("\n");
            sb.Append("  HostingAdminEmail: ").Append(HostingAdminEmail).Append("\n");
            sb.Append("  DiskQuota: ").Append(DiskQuota).Append("\n");
            sb.Append("  FtpQuota: ").Append(FtpQuota).Append("\n");
            sb.Append("  BandwidthQuota: ").Append(BandwidthQuota).Append("\n");
            sb.Append("  DbQuota: ").Append(DbQuota).Append("\n");
            sb.Append("  DbMaxSize: ").Append(DbMaxSize).Append("\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((HostingAccount)obj);
        }

        /// <summary>
        /// Returns true if HostingAccount instances are equal
        /// </summary>
        /// <param name="other">Instance of HostingAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HostingAccount other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.HostingName == other.HostingName ||
                    this.HostingName != null &&
                    this.HostingName.Equals(other.HostingName)
                ) && 
                (
                    this.HostingAdminEmail == other.HostingAdminEmail ||
                    this.HostingAdminEmail != null &&
                    this.HostingAdminEmail.Equals(other.HostingAdminEmail)
                ) && 
                (
                    this.DiskQuota == other.DiskQuota ||
                    this.DiskQuota != null &&
                    this.DiskQuota.Equals(other.DiskQuota)
                ) && 
                (
                    this.FtpQuota == other.FtpQuota ||
                    this.FtpQuota != null &&
                    this.FtpQuota.Equals(other.FtpQuota)
                ) && 
                (
                    this.BandwidthQuota == other.BandwidthQuota ||
                    this.BandwidthQuota != null &&
                    this.BandwidthQuota.Equals(other.BandwidthQuota)
                ) && 
                (
                    this.DbQuota == other.DbQuota ||
                    this.DbQuota != null &&
                    this.DbQuota.Equals(other.DbQuota)
                ) && 
                (
                    this.DbMaxSize == other.DbMaxSize ||
                    this.DbMaxSize != null &&
                    this.DbMaxSize.Equals(other.DbMaxSize)
                ) && 
                (
                    this.Region == other.Region ||
                    this.Region != null &&
                    this.Region.Equals(other.Region)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.HostingName != null)
                    hash = hash * 59 + this.HostingName.GetHashCode();
                if (this.HostingAdminEmail != null)
                    hash = hash * 59 + this.HostingAdminEmail.GetHashCode();
                if (this.DiskQuota != null)
                    hash = hash * 59 + this.DiskQuota.GetHashCode();
                if (this.FtpQuota != null)
                    hash = hash * 59 + this.FtpQuota.GetHashCode();
                if (this.BandwidthQuota != null)
                    hash = hash * 59 + this.BandwidthQuota.GetHashCode();
                if (this.DbQuota != null)
                    hash = hash * 59 + this.DbQuota.GetHashCode();
                if (this.DbMaxSize != null)
                    hash = hash * 59 + this.DbMaxSize.GetHashCode();
                if (this.Region != null)
                    hash = hash * 59 + this.Region.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(HostingAccount left, HostingAccount right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(HostingAccount left, HostingAccount right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
