/*
 * Wish Fabric Api - Middleware to Fabric
 *
 * Wish Fabric API (Integration)
 *
 * OpenAPI spec version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Grant :  IEquatable<Grant>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Grant" /> class.
        /// </summary>
        /// <param name="DatabaseId">Database identifier (required).</param>
        /// <param name="Permissions">Grant details.</param>
        public Grant(string DatabaseId = null, string Permissions = null)
        {
            // to ensure "DatabaseId" is required (not null)
            if (DatabaseId == null)
            {
                throw new InvalidDataException("DatabaseId is a required property for Grant and cannot be null");
            }
            else
            {
                this.DatabaseId = DatabaseId;
            }
            this.Permissions = Permissions;
            
        }

        /// <summary>
        /// Database identifier
        /// </summary>
        /// <value>Database identifier</value>
        [DataMember(Name="database_id")]
        public string DatabaseId { get; set; }

        /// <summary>
        /// Grant details
        /// </summary>
        /// <value>Grant details</value>
        [DataMember(Name="permissions")]
        public string Permissions { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Grant {\n");
            sb.Append("  DatabaseId: ").Append(DatabaseId).Append("\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Grant)obj);
        }

        /// <summary>
        /// Returns true if Grant instances are equal
        /// </summary>
        /// <param name="other">Instance of Grant to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Grant other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.DatabaseId == other.DatabaseId ||
                    this.DatabaseId != null &&
                    this.DatabaseId.Equals(other.DatabaseId)
                ) && 
                (
                    this.Permissions == other.Permissions ||
                    this.Permissions != null &&
                    this.Permissions.Equals(other.Permissions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.DatabaseId != null)
                    hash = hash * 59 + this.DatabaseId.GetHashCode();
                if (this.Permissions != null)
                    hash = hash * 59 + this.Permissions.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Grant left, Grant right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Grant left, Grant right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
