/*
 * Wish Fabric Api - Middleware to Fabric
 *
 * Wish Fabric API (Integration)
 *
 * OpenAPI spec version: 1.0.1
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class HostingAccount :  IEquatable<HostingAccount>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HostingAccount" /> class.
        /// </summary>
        /// <param name="HostingAccountId">Fabric hosting_acount_id (PK) (required).</param>
        /// <param name="HostingName">HostingAccount name (primary domain) (required).</param>
        /// <param name="HostingAdminEmail">admin email for hosting account.</param>
        public HostingAccount(long? HostingAccountId = null, string HostingName = null, string HostingAdminEmail = null)
        {
            // to ensure "HostingAccountId" is required (not null)
            if (HostingAccountId == null)
            {
                throw new InvalidDataException("HostingAccountId is a required property for HostingAccount and cannot be null");
            }
            else
            {
                this.HostingAccountId = HostingAccountId;
            }
            // to ensure "HostingName" is required (not null)
            if (HostingName == null)
            {
                throw new InvalidDataException("HostingName is a required property for HostingAccount and cannot be null");
            }
            else
            {
                this.HostingName = HostingName;
            }
            this.HostingAdminEmail = HostingAdminEmail;
            
        }

        /// <summary>
        /// Fabric hosting_acount_id (PK)
        /// </summary>
        /// <value>Fabric hosting_acount_id (PK)</value>
        [DataMember(Name="hosting_account_id")]
        public long? HostingAccountId { get; set; }

        /// <summary>
        /// HostingAccount name (primary domain)
        /// </summary>
        /// <value>HostingAccount name (primary domain)</value>
        [DataMember(Name="hosting_name")]
        public string HostingName { get; set; }

        /// <summary>
        /// admin email for hosting account
        /// </summary>
        /// <value>admin email for hosting account</value>
        [DataMember(Name="hosting_admin_email")]
        public string HostingAdminEmail { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HostingAccount {\n");
            sb.Append("  HostingAccountId: ").Append(HostingAccountId).Append("\n");
            sb.Append("  HostingName: ").Append(HostingName).Append("\n");
            sb.Append("  HostingAdminEmail: ").Append(HostingAdminEmail).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((HostingAccount)obj);
        }

        /// <summary>
        /// Returns true if HostingAccount instances are equal
        /// </summary>
        /// <param name="other">Instance of HostingAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HostingAccount other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.HostingAccountId == other.HostingAccountId ||
                    this.HostingAccountId != null &&
                    this.HostingAccountId.Equals(other.HostingAccountId)
                ) && 
                (
                    this.HostingName == other.HostingName ||
                    this.HostingName != null &&
                    this.HostingName.Equals(other.HostingName)
                ) && 
                (
                    this.HostingAdminEmail == other.HostingAdminEmail ||
                    this.HostingAdminEmail != null &&
                    this.HostingAdminEmail.Equals(other.HostingAdminEmail)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.HostingAccountId != null)
                    hash = hash * 59 + this.HostingAccountId.GetHashCode();
                if (this.HostingName != null)
                    hash = hash * 59 + this.HostingName.GetHashCode();
                if (this.HostingAdminEmail != null)
                    hash = hash * 59 + this.HostingAdminEmail.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(HostingAccount left, HostingAccount right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(HostingAccount left, HostingAccount right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
